# Generated by Django 5.2.17 on 2026-09-01 19:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankingCustomer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=64, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=32, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('pin_hash', models.CharField(max_length=255)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biometric_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banking_customer', to='biometrics.biometricuser')),
            ],
            options={
                'ordering': ['full_name', 'customer_id'],
            },
        ),
    ]
