# Generated by Django 5.2.17 on 2026-09-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0002_bankingcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticationattempt',
            name='fusion_reason_code',
            field=models.CharField(blank=True, choices=[('ALL_MODALITIES_VALID', 'All Modalities Valid'), ('SINGLE_MODALITY_HIGH_CONFIDENCE', 'Single Modality High Confidence'), ('IRIS_NOT_DETECTED', 'Iris Not Detected'), ('IRIS_QUALITY_TOO_LOW', 'Iris Quality Too Low'), ('VOICE_QUALITY_TOO_LOW', 'Voice Quality Too Low'), ('VOICE_NO_SPEECH_ACTIVITY', 'No Speech Activity'), ('FUSION_INCONCLUSIVE', 'Fusion Inconclusive'), ('NO_VALID_MODALITY', 'No Valid Modality'), ('REJECTED_MISMATCH', 'Rejected: Mismatch'), ('REJECTED_SPOOF', 'Rejected: Spoof'), ('PROCESSING_ERROR', 'Processing Error')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='authenticationattempt',
            name='iris_detection_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authenticationattempt',
            name='iris_valid_measurement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='authenticationattempt',
            name='decision',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('REJECTED_MISMATCH', 'Rejected: Mismatch'), ('REJECTED_SPOOF', 'Rejected: Spoof'), ('RETRY_REQUIRED', 'Retry Required'), ('PROCESSING_ERROR', 'Processing Error')], default='PROCESSING_ERROR', max_length=32),
        ),
    ]
