# Generated by Django 5.2.17 on 2026-09-14 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0003_authenticationattempt_fusion_reason_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authentication_attempts', to='biometrics.biometricuser'),
        ),
    ]
