# Generated by Django 5.2.17 on 2026-09-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0004_alter_authenticationattempt_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticationattempt',
            name='voice_valid_measurement',
            field=models.BooleanField(default=False),
        ),
    ]
