# Generated by Django 5.2.17 on 2026-09-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0005_authenticationattempt_voice_valid_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticationattempt',
            name='face_detection_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authenticationattempt',
            name='face_normalized_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authenticationattempt',
            name='face_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authenticationattempt',
            name='face_quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authenticationattempt',
            name='face_raw_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authenticationattempt',
            name='face_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authenticationattempt',
            name='face_valid_measurement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authenticationattempt',
            name='fusion_face_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='biometricuser',
            name='face_quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biometricuser',
            name='face_sample_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='biometricuser',
            name='face_template_encrypted',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='biometricuser',
            name='iris_sample_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='biometricuser',
            name='iris_template_encrypted',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='biometricuser',
            name='template_version',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='biometricuser',
            name='voice_sample_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='biometricuser',
            name='voice_template_encrypted',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='authenticationattempt',
            name='fusion_reason_code',
            field=models.CharField(blank=True, choices=[('ALL_MODALITIES_VALID', 'All Modalities Valid'), ('SINGLE_MODALITY_HIGH_CONFIDENCE', 'Single Modality High Confidence'), ('IRIS_NOT_DETECTED', 'Iris Not Detected'), ('IRIS_QUALITY_TOO_LOW', 'Iris Quality Too Low'), ('VOICE_QUALITY_TOO_LOW', 'Voice Quality Too Low'), ('VOICE_NO_SPEECH_ACTIVITY', 'No Speech Activity'), ('FACE_NOT_DETECTED', 'Face Not Detected'), ('FACE_QUALITY_TOO_LOW', 'Face Quality Too Low'), ('MULTIPLE_FACES', 'Multiple Faces'), ('FUSION_INCONCLUSIVE', 'Fusion Inconclusive'), ('NO_VALID_MODALITY', 'No Valid Modality'), ('REJECTED_MISMATCH', 'Rejected: Mismatch'), ('REJECTED_SPOOF', 'Rejected: Spoof'), ('PROCESSING_ERROR', 'Processing Error')], max_length=64, null=True),
        ),
    ]
